# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb15442b34ac046eafb7597f82467372229b41fa2e191fade6da46d78e9131e1a2cafb0fe22cb45be763bf25490ae5528edbb8c412dd624c59f5f1bfa0b6d092

test:
  secret_key_base: a56daab179f967cea7fee22737600b1c9562e493e92ae277886d249e4c245ca4f4e4aa5a21a09c08219efd14418f3568e610082b7f16d69cf200b342271c4e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
